#!/usr/bin/env bash
# اضافه کردن یه سرور استریم جدید به مجموعه (WireGuard tunnel + Redis مشترک +
# دیپلوی کد + systemd + وزن nginx متناسب با پهنای‌باند فیزیکی سرور جدید).
#
# پیش‌نیاز (تنها قدم دستی که قابل حذف نیست): کلید عمومی SSH این سرور (سرور
# اول/کنترل) باید از قبل توی ~/.ssh/authorized_keys سرور جدید اضافه شده باشه.
#
# استفاده:
#   scripts/add_stream_node.sh <name> <ssh_host> <ssh_port> <mbps>
#
# مثال:
#   scripts/add_stream_node.sh server3 1.2.3.4 22 300
#
# این اسکریپت باید روی سرور اول (کنترل) و با دسترسی root اجرا بشه.

set -euo pipefail

if [ "$#" -ne 4 ]; then
    echo "استفاده: $0 <name> <ssh_host> <ssh_port> <mbps>" >&2
    exit 1
fi

NEW_NAME="$1"
NEW_HOST="$2"
NEW_PORT="$3"
NEW_MBPS="$4"

REPO_DIR="/root/dlst-filebot"
NODES_FILE="$REPO_DIR/scripts/nodes.conf"
WG_CONF="/etc/wireguard/wg0.conf"
WG_LOCAL_PUBKEY_FILE="/etc/wireguard/server1_public.key"
NGINX_SITE="/etc/nginx/sites-available/nf-panel.ir"
UPSTREAM_BEGIN="# BEGIN filebot upstream (auto-generated by scripts/add_stream_node.sh)"
UPSTREAM_END="# END filebot upstream"

ssh_new() { ssh -p "$NEW_PORT" -o StrictHostKeyChecking=accept-new "root@$NEW_HOST" "$@"; }

# خط‌های داده‌ی nodes.conf بدون کامنت‌ها و خط‌های خالی (۳ خط کامنت توضیحی بالای فایل)
data_lines() { grep -vE '^\s*#' "$NODES_FILE" | grep -vE '^\s*$'; }

if grep -qE "^\s*${NEW_NAME}\s" "$NODES_FILE"; then
    echo "خطا: نودی به نام '$NEW_NAME' از قبل تو $NODES_FILE هست" >&2
    exit 1
fi

echo "== [۱/۹] تست اتصال SSH به $NEW_HOST:$NEW_PORT =="
ssh_new "echo ok" >/dev/null

echo "== [۲/۹] تعیین IP بعدی تونل =="
LAST_OCTET=$(data_lines | awk '{print $2}' | grep -oP '10\.10\.0\.\K[0-9]+' | sort -n | tail -1)
NEXT_OCTET=$((LAST_OCTET + 1))
TUNNEL_IP="10.10.0.$NEXT_OCTET"
echo "   IP تونل جدید: $TUNNEL_IP"

echo "== [۳/۹] نصب پیش‌نیازها و ساخت کلید WireGuard روی سرور جدید =="
ssh_new "apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wireguard python3-venv rsync git"
ssh_new "umask 077; mkdir -p /etc/wireguard; [ -f /etc/wireguard/privatekey ] || (wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey)"
NEW_PUBKEY=$(ssh_new "cat /etc/wireguard/publickey")

echo "== [۴/۹] اضافه کردن peer به تونل سرور اول (بدون قطع تونل‌های فعلی) =="
if ! grep -qF "$NEW_PUBKEY" "$WG_CONF"; then
    {
        echo ""
        echo "[Peer]"
        echo "PublicKey = $NEW_PUBKEY"
        echo "AllowedIPs = $TUNNEL_IP/32"
    } >> "$WG_CONF"
fi
wg syncconf wg0 <(wg-quick strip wg0)

echo "== [۵/۹] ساخت wg0.conf روی سرور جدید و بالا آوردن تونل =="
LOCAL_PUBKEY=$(cat "$WG_LOCAL_PUBKEY_FILE")
LOCAL_ENDPOINT_IP=$(curl -s https://ifconfig.me)
ssh_new "cat > /etc/wireguard/wg0.conf" <<EOF
[Interface]
PrivateKey = $(ssh_new "cat /etc/wireguard/privatekey")
Address = $TUNNEL_IP/24

[Peer]
PublicKey = $LOCAL_PUBKEY
Endpoint = $LOCAL_ENDPOINT_IP:51820
AllowedIPs = 10.10.0.1/32
PersistentKeepalive = 25
EOF
ssh_new "systemctl enable --now wg-quick@wg0"

echo "== [۶/۹] تست تونل =="
for i in 1 2 3 4 5; do
    if ping -c 1 -W 2 "$TUNNEL_IP" >/dev/null 2>&1; then
        echo "   تونل وصل شد."
        break
    fi
    [ "$i" -eq 5 ] && { echo "خطا: تونل بعد از ۵ تلاش وصل نشد" >&2; exit 1; }
    sleep 2
done

echo "== [۷/۹] انتقال کد و آماده‌سازی venv روی سرور جدید =="
rsync -az -e "ssh -p $NEW_PORT" \
    --exclude='venv' --exclude='sessions' --exclude='.env' \
    --exclude='bot.log' --exclude='stream_node.log' --exclude='__pycache__' \
    --exclude='app/__pycache__' --exclude='.git' \
    "$REPO_DIR/" "root@$NEW_HOST:$REPO_DIR/"
ssh_new "mkdir -p $REPO_DIR/sessions"
ssh_new "cd $REPO_DIR && python3 -m venv venv && venv/bin/pip install --quiet -r requirements.txt"

echo "== [۸/۹] ثبت نود جدید در اینونتوری و آپدیت TOTAL_SERVER_MBPS همه‌ی سرورها =="
echo "$NEW_NAME   $TUNNEL_IP   $NEW_HOST   $NEW_PORT   $NEW_MBPS" >> "$NODES_FILE"

TOTAL_MBPS=$(data_lines | awk '{sum += $5} END {print sum}')
echo "   مجموع پهنای‌باند جدید: ${TOTAL_MBPS} Mbps"

REDIS_URL_LOCAL=$(grep -oP '^REDIS_URL=\K.*' "$REPO_DIR/.env")
REDIS_PASS=$(echo "$REDIS_URL_LOCAL" | grep -oP 'redis://:\K[^@]+')

# آپدیت .env لوکال (سرور اول)
sed -i -E "s|^TOTAL_SERVER_MBPS=.*|TOTAL_SERVER_MBPS=${TOTAL_MBPS}|" "$REPO_DIR/.env"
if ! grep -q "^TOTAL_SERVER_MBPS=" "$REPO_DIR/.env"; then
    echo "TOTAL_SERVER_MBPS=${TOTAL_MBPS}" >> "$REPO_DIR/.env"
fi

# تابع ساخت .env مخصوص یه نود ریموت (REDIS_URL از طریق تونل + TOTAL_SERVER_MBPS جدید)
build_remote_env() {
    sed -E \
        -e "s|^REDIS_URL=.*|REDIS_URL=redis://:${REDIS_PASS}@10.10.0.1:6379/0|" \
        -e "s|^TOTAL_SERVER_MBPS=.*|TOTAL_SERVER_MBPS=${TOTAL_MBPS}|" \
        "$REPO_DIR/.env"
}

# پوش کردن .env جدید + ری‌استارت روی همه‌ی نودهای ریموتِ موجود (چون TOTAL عوض شده)
data_lines | grep -v '^local' | while read -r name tip host port mbps; do
    [ "$name" = "$NEW_NAME" ] && continue   # خودِ نود جدید جداگانه پایین‌تر ست می‌شه
    echo "   آپدیت .env و ری‌استارت روی نود موجود: $name"
    build_remote_env | ssh -p "$port" "root@$host" "cat > $REPO_DIR/.env"
    ssh -p "$port" "root@$host" "systemctl restart stream-node.service" </dev/null || true
done

# ساخت systemd unit + .env روی نود تازه اضافه‌شده
build_remote_env | ssh_new "cat > $REPO_DIR/.env"
ssh_new "cat > /etc/systemd/system/stream-node.service" <<EOF
[Unit]
Description=dlst-filebot stream-only node ($NEW_NAME)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$REPO_DIR
ExecStart=$REPO_DIR/venv/bin/python3 -m app.stream_node
Restart=always
RestartSec=5
StandardOutput=append:$REPO_DIR/stream_node.log
StandardError=append:$REPO_DIR/stream_node.log

[Install]
WantedBy=multi-user.target
EOF
ssh_new "systemctl daemon-reload && systemctl enable --now stream-node.service"

echo "== [۹/۹] آپدیت وزن nginx و ری‌استارت سرور اول =="
{
    echo "$UPSTREAM_BEGIN"
    echo "upstream filebot_backends {"
    data_lines | while read -r name tip host port mbps; do
        if [ "$name" = "local" ]; then
            echo "    server 127.0.0.1:8085 weight=${mbps};"
        else
            echo "    server ${tip}:8085 weight=${mbps};"
        fi
    done
    echo "}"
    echo "$UPSTREAM_END"
} > /tmp/filebot_upstream_block.conf

awk -v begin="$UPSTREAM_BEGIN" -v end="$UPSTREAM_END" -v blockfile=/tmp/filebot_upstream_block.conf '
    $0 == begin { skip=1; while ((getline line < blockfile) > 0) print line; close(blockfile); next }
    $0 == end { skip=0; next }
    !skip { print }
' "$NGINX_SITE" > /tmp/nf-panel.ir.new
mv /tmp/nf-panel.ir.new "$NGINX_SITE"
rm -f /tmp/filebot_upstream_block.conf

nginx -t
systemctl reload nginx

# ری‌استارت سرور اول (main.py) تا TOTAL_SERVER_MBPS جدید رو بخونه
OLD_PID=$(pgrep -f "venv/bin/python3 -m app.main" || true)
[ -n "$OLD_PID" ] && kill "$OLD_PID"
sleep 2
cd "$REPO_DIR"
setsid nohup venv/bin/python3 -m app.main > bot.log 2>&1 < /dev/null &
disown

echo ""
echo "✅ نود '$NEW_NAME' ($TUNNEL_IP, ${NEW_MBPS}Mbps) اضافه شد. مجموع پهنای‌باند: ${TOTAL_MBPS}Mbps"
